language: cpp
compiler:
  - gcc
  - clang
# Build MCServer
script: cmake . -DCMAKE_BUILD_TYPE=RELEASE && make -j 2

# Notification Settings
notifications:
  email:
    on_success: change
    on_failure: always
