language: cpp
compiler:
  - gcc
  - clang
# Build MCServer
script: cmake . -DCMAKE_BUILD_TYPE=RELEASE -DSELF_TEST=1 && make -j 2 && cd MCServer/ && ./MCServer

# Notification Settings
notifications:
  email:
    on_success: change
    on_failure: always
